/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/enquiry': typeof EnquiryRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/enquiry': typeof EnquiryRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/enquiry': typeof EnquiryRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/enquiry'
    | '/location'
    | '/login'
    | '/offers'
    | '/services'
    | '/settings'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/enquiry'
    | '/location'
    | '/login'
    | '/offers'
    | '/services'
    | '/settings'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/enquiry'
    | '/location'
    | '/login'
    | '/offers'
    | '/services'
    | '/settings'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  EnquiryRoute: typeof EnquiryRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  EnquiryRoute: EnquiryRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
